{
 "title": "Telemetry_224",
 "time": { "from": "now-20s", "to": "now" },
 "refresh": "300ms",
 "panels": [
  {
   "title": "Voltage X Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "aVoltage", "legendFormat": "Voltage" },
    { "expr": "aAccumulatorCurrent", "legendFormat": "Current" }
   ]
  },
  {
   "title": "Wheel Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    { "expr": "aFrontLeftWheelSpeed", "legendFormat": "Front Left" },
    { "expr": "aFrontRightWheelSpeed", "legendFormat": "Front Right" },
    { "expr": "aRearLeftWheelSpeed", "legendFormat": "Rear Left" },
    { "expr": "aRearRightWheelSpeed", "legendFormat": "Rear Right" }
   ]
  },
  {
   "title": "Track",
   "type": "xychart",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "targets": [
    { "expr": "aLatitude", "legendFormat": "Latitude" },
    { "expr": "aLongitude", "legendFormat": "Longitude" }
   ]
  },
  {
   "title": "Steering Angle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    { "expr": "aSteeringAngle", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Power x RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "aPower", "legendFormat": "Power" },
    { "expr": "aRpm", "legendFormat": "RPM" }
   ]
  },
  {
   "title": "Brake Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    { "expr": "aBrakePressure", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "G x G",
   "type": "xychart",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 6 },
   "targets": [
    { "expr": "aLateralForce", "legendFormat": "LateralG" },
    { "expr": "aLongitudinalForce", "legendFormat": "LongitudinalG" }
   ]
  },
  {
   "title": "Suspension",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aFrontLeftSuspension", "legendFormat": "Front Left" },
    { "expr": "aFrontRightSuspension", "legendFormat": "Front Right" }
   ]
  },
  {
   "title": "Accumulator",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aAccumulatorTemperature", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Motor",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aMotorTemperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "APPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aApps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "BSE",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aBse", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SoC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aStateOfCharge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fails",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aBmsFail", "legendFormat": "BMS" },
    { "expr": "aBspdFail", "legendFormat": "BSPD" },
    { "expr": "aEcuFail", "legendFormat": "ECU" },
    { "expr": "aImdFail", "legendFormat": "IMD" },
    { "expr": "aInverterFail", "legendFormat": "Inverter" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aRearLeftSuspension", "legendFormat": "Rear Left" },
    { "expr": "aRearRightSuspension", "legendFormat": "Rear Right" }
   ]
  }
 ]
}