{
 "title": "223 - Geral",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Corrente Acumulador",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "aCurrent" }
   ]
  },
  {
   "title": "Tensão Acumulador",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "aVoltage" }
   ]
  },
  {
   "title": "Potência Acumulador",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "aPower" }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "aRPM" }
   ]
  },
  {
   "title": "Velocidade",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    { "expr": "aWheelSpeed" }
   ]
  },
  {
   "title": "APPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aAPPS" }
   ]
  },
  {
   "title": "BSE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aBSE" }
   ]
  },
  {
   "title": "Temperatura Planetária",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aTemperaturePlanetary" }
   ]
  },
  {
   "title": "Temperatura Motor",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aTemperatureMotor" }
   ]
  },
  {
   "title": "Temperatura Inversor",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aTemperatureInverter" }
   ]
  },
  {
   "title": "Temperatura Acumulador - MED",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aTemperatureAcumulatorAvg" }
   ]
  },
  {
   "title": "Temperatura Acumulador - PEAK",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aTemperatureAcumulatorPeak" }
   ]
  },
  {
   "title": "SoC",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aSoC" }
   ]
  },
  {
   "title": "Falha BMS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aBMSFail" }
   ]
  },
  {
   "title": "Falha BSPD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aBSPDFail" }
   ]
  },
  {
   "title": "Falha IMD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aIMDFail" }
   ]
  },
  {
   "title": "Falha ECU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aECUFail" }
   ]
  },
  {
   "title": "DCL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aDCL" }
   ]
  },
  {
   "title": "Pressão na linha de freio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aBrakePressure" }
   ]
  }
 ]
}